### ISSUE TITLE
Benchmark against QuTiP 4.1

### ISSUE THREAD

**Issue by nonhermitian** [qojulia/QuantumOptics.jl#116]
Would be interesting to see benchmarks against QuTiP 4.1. QuTiP 3.1 is a bit dated.

**Comment by bastikr** [comment]
Yes I absolutely agree. I just realized that on archlinux the AUR package for python2 is qutip 4.0 while for python3 it is qutip 3.1. I will rerun the tests tomorrow for the latest official release. Thanks for the heads up!

**Comment by nonhermitian** [comment]
No problem.  Good to see someone getting into open-source quantum simulation.

**Comment by bastikr** [comment]
I ran the benchmarks on qutip 4.1 and for partial traces it is a huge improvement. However, for the operator based tests (expect_operator, qfunc_operator ans variance_operator) it gives wrong results. I submitted an issue at https://github.com/qutip/qutip/issues/681.

**Comment by bastikr** [comment]
All benchmarks displayed on the website are now done with QuTiP 4.1.
