### ISSUE TITLE
Option to disable all checks for better performance (like @inbounds)

### ISSUE THREAD

**Issue by bastikr** [qojulia/QuantumOptics.jl#121]
__

**Comment by i-apellaniz** [comment]
I did have something like this implemented in a small tutorial. Basically one has to use a flag which tells whether it should be checked or not. This doesn't avoid the code branching, i.e., the checking is still there, but AFAIK, you cannot do the way @inbounds does yet.
```julia
const HILB_CHECK = Ref(true)

macro hilbertcheck(ex)
    # eval escaped ex if flag is true
    :(HILB_CHECK[] && $(esc(ex)))
end

macro inhilbert(ex)
    # eval wrapped code which turns off and on the hilbert checking flag
    :(HILB_CHECK.x = false; $(esc(ex)); HILB_CHECK.x = true)
end
```

Now it should be good to go. Whenever one thinks that an expression is used for checking the hilbert spaces (known as "basis" in QuantumOptics.jl) one should annotate it with `@hilbertcheck`. Just use `@inhilbert` to remove the checkings.

```julia
julia> struct Quantum
           basis
           data
       end          

julia> function foo(q::Quantum, p::Quantum)
           @hilbertcheck q.basis == p.basis || throw("Basis don't coincide")
           "foo des nothing... but HELLO from foo"
       end

julia> q = Quantum(1, [1]); p = Quantum(2, [2])

julia> foo(q, p)

julia> @inhilbert x = foo(q, p); x # here we skip the checking
"foo des nothing... but HELLO from foo"
```

**Comment by david-pl** [comment]
The latest master branch has this feature now. Thanks for the help @i-apellaniz
