### ISSUE TITLE
qojulia.org/benchmarks does not load its plots

### ISSUE THREAD

**Issue by Krastanov** [qojulia/QuantumOptics.jl#170]
In Firefox 55 and Chrome 60 on Debian the plots from the benchmarks do not load.

**Comment by bastikr** [comment]
Thank you for the report! It is probably caused by changes in one of the used javascript libraries. @lostermann can you look into it?

**Comment by bastikr** [comment]
It turned out to be a mistake in the automatic build script. It assumed that the correct branch of the benchmarks is checked out. Not sure if we should change the build script, but for now the benchmarks are displayed correctly again.
