### ISSUE TITLE
Unneeded factor of 0.5 in tracenorm

### ISSUE THREAD

**Issue by david-pl** [qojulia/QuantumOptics.jl#171]
I noticed that there is a factor of 0.5 in the definition of the tracenorm function. Is this on purpose? To me it seems like this was a typo from the beginning, since also the docstring states that it uses this relation. However, a more common definition would be without the 0.5. This would also be more intuitive, since with the current implementation a density matrix (or any matrix with trace 1) has a tracenorm of 0.5 instead of 1 (which is what at least I would have expected).

**Comment by bastikr** [comment]
My mistake - the factor 1/2 is only needed for trace distances, not trace norms. #172 should fix this.

**Comment by david-pl** [comment]
Merged #172
