### ISSUE TITLE
tracenorm changes the given operator

### ISSUE THREAD

**Issue by bastikr** [qojulia/QuantumOptics.jl#173]
The following lines in the tracenorm function change the given dense operator rho:

https://github.com/qojulia/QuantumOptics.jl/blob/ca191f5a1ef0d08588ec16cd44c28bf161a836c0/src/metrics.jl#L22-L25

This definitely should not happen. Also just making the diagonal real might be the wrong approach. Maybe we should rethink how we want to treat non-hermitian and nearly hermitian operators. Any thoughts?

**Comment by david-pl** [comment]
The change of the operator can be easily avoided by copying, i.e. `data = copy(rho.data)`.

As for the real diagonal, we could sacrifice some efficiency by implementing a check for the Hermiticity of `rho` and then call `tracenorm_general` if it is not. Or we simply always compute the eigenvalues of the product `dagger(rho)*rho` which is guaranteed to be Hermitian and then take the sum over the square root of them (so basically always use `tracenorm_general`).

I have to admit, though, that I am not too much of a fan of either of these approaches. Do you have a better idea?

**Comment by david-pl** [comment]
Fixed by #175
