### ISSUE TITLE
SMEs in stochastic.master and stochastic.master_dynamic

### ISSUE THREAD

**Issue by joshcombes** [qojulia/QuantumOptics.jl#209]
I would like to suggest a change to the way SMEs are called in QuantumOptics.jl.

Consider the H object 

<img width="618" alt="untitled" src="https://user-images.githubusercontent.com/2394563/38058606-52e7a188-3298-11e8-9074-6c862e2f02b9.png">

which takes X and \rho as arguments. The first equation is what I am calling the "linear version of H".  Perhaps the default setting in "stochastic.master" and "stochastic.master_dynamic" should be with the expectation part calculated and one could imagine using flag to switch to the linear version.

**Comment by david-pl** [comment]
Thanks for raising that point!

I agree that the implementation should be changed. Hopefully, I can get to it in the coming days.

**Comment by david-pl** [comment]
@joshcombes I implemented the non-linear SME as default for all stochastic master equations. You can switch back to the linear form by setting the optional argument `nonlinear=false`. I will merge this soon.

**Comment by david-pl** [comment]
@joshcombes I merged the PR. I will leave this issue open until the documentation is updated accordingly. I'll hold off with a new release until then too. In the meantime you can just checkout the master branch

**Comment by joshcombes** [comment]
@david-pl I started playing with it in the new branch yesterday. I'll switch back to master and keep using it. Again many thanks.

**Comment by david-pl** [comment]
Draft a new release including the changes. Documentation is updated and on-line.
