### ISSUE TITLE
Eigenstates of Hermitian SparseOperators

### ISSUE THREAD

**Issue by vtorggler** [qojulia/QuantumOptics.jl#216]
Calculating eigenstates or eigenenergies of Hermitian SparseOperators is very slow. This is due to the Julia eigs function, which seems to have a problem with the type Hermitian. One should not convert the sparse matrix, I guess.

For a Hermitian SparseOperator H
`eigs(H.data, nev = 100, which = :SR)`
is fast,
`eigs(Hermitian(H.data), nev = 100, which = :SR)`
is about 50 times slower.

Also, in the API it says that it returns the 6 lowest eigenvalues by default. But it defaults to length(basis(op)) eigenvalues. This also doesn't make to much sense for the Lanczos algorithm, which is good for calculating only "some" eigenvalues. So maybe one should rather use the eigs default.

**Comment by david-pl** [comment]
The latest commit changes the function according to your suggestions.
