### ISSUE TITLE
Conjugate of operators

### ISSUE THREAD

**Issue by vtorggler** [qojulia/QuantumOptics.jl#217]
The conjugate of operators
`conj(H)`
does not have an effect. It also does not give an error. I think this is dangerous.

In other words,
`conj(H).data == conj(H.data)`
it not necessarily true.

**Comment by david-pl** [comment]
This actually has nothing to do with QuantumOptics, but it's a Julia issue. There is a method defined for `conj` in `Base.operators` which is just
```julia
conj(x) = x
```
so it works for literally anything,
```julia
julia> conj("anything")
"anything"

However, this is already fixed (see https://github.com/JuliaLang/julia/pull/26288), so once `v0.7` is released, it won't be a problem anymore.

**Comment by david-pl** [comment]
The latest commit implements a method of `conj` for dense and sparse operators, and otherwise throws an error message.
