### ISSUE TITLE
Splitting base functionality of QuantumOptics into a separate package

### ISSUE THREAD

**Issue by david-pl** [qojulia/QuantumOptics.jl#258]
Following a discussion with @PhilipVinc on gitter: it makes sense to split QuantumOptics into sub-packages. At the very least into two, where one does not do any time evolution and thus is independent of any DiffEq packages (say a package called QuantumOpticsBase.jl).

Things that should definitely go into QuantumOpticsBase:
- Bases
- States
- Operators
- Superoperators
- Specific Hilbert spaces (fock, spin, etc.)

Things that should probably go into QuantumOpticsBase:
- Metrics
- Pauli (cc @atombear)
- Phase-space methods
- Spectral analysis
- Transformations

Everything else should be kept separately. For now it should probably suffice to load QuantumOpticsBase.jl into QuantumOptics.jl and keep all the remaining things there as well.

It's important to proceed in a structured way here:
- [x] Create a new repository for QuantumOpticsBase.jl
- [x] Put all the stuff mentioned above into QuantumOpticsBase
- [x] Register QuantumOpticsBase
- [x] Remove unnecessary things from QuantumOptics.jl
- [x] Document the API of QuantumOpticsBase separately

**Comment by PhilipVinc** [comment]
I agree with your _definitely_ list.
About the other things... I'd like to share this simple load time benchmark, done by substituting all `include("xyz")` statements in `QuantumOptics.jl` with `@timeit to "xyz" include("xyz")` statements.

Every line is the time spent loading a specific file. See [this gist](https://gist.github.com/PhilipVinc/3457f930b7fba1a011f6fdd5670b59d8)

**Comment by PhilipVinc** [comment]
My idea for `QuantumOpticsBase` is for a package to be able to 
- use the same base abstract types of QuantumOptics and declare other operators, without drawing in the whole dependency tree.
- Access handy methods like `create`, `destruct`, `sigmax/y/z` to build hamiltonians, without needing to depend on other heavy dependencies.
- Use Hilbert bases and the logic associated. (Why should I reimplement it, as it's already very nicely implemented in QO.jl?)
- Have a few essential methods to work with those objects (operator product, tensor product of operators, bases..., norms, what else?)

A nice way to think about this is to try to keep the dependencies of `QuantumOpticsBase.jl` to a minimum.

As such, I believe that 
- Phase space methods should not be included 
- I'm torn on SpectralAnalysis. From my ideas listed above I'd say we should not include them. And we could get rid of ArPack dependency. But it's also a fairly lightweight dependency, so maybe it would not be too bad including it. 
  - Maybe we could exclude it, and in the future if the need of someone arises/people ask for it, we can move it later.
- Transformations are handy things to work with bases, and have no dependencies. we could include them...

I don't think `Phase-Space` methods should go there.
I would argue

**Comment by alastair-marshall** [comment]
Just wanted to say that as someone who currently uses QuantumOptics mainly for Hilbert bases and quickly creating Hamiltonians to test things I would really appreciate this change! 

I'd also like to help out wherever I can, although I've only recently started using Julia. 

(P.S. I agree with David that Pauli stuff should go into the QOBase)

**Comment by david-pl** [comment]
There you go: https://github.com/qojulia/QuantumOpticsBase.jl

I included:
- everything from the *definitely* list
- Pauli
- Transformations
- Metrics

I excluded `spectralanalysis` for now since it's really just a thin wrap around Julia's diagonalization routines anyway. @PhilipVinc I don't think `metrics` depends on `spectralanalysis`. Eigenvalues in `metrics` are computed from the `.data` field or did I miss something there?

Regarding the `FFTOperator`: I agree it's unfortunate to have `FFTW` just for this. However, it would feel a bit inconsistent if we include every subtype of `AbstractOperator` except this one. So I kind of want to keep it.

I still have to make some changes to new repository (like changing the readme and stuff). Other than such superficial things I think it's done, though.

**Comment by PhilipVinc** [comment]
I think you can remove the `WignerSymbols` dependency

**Comment by atombear** [comment]
This certainly seems fine to me - I'm happy to help wit the refactor.

**Comment by david-pl** [comment]
Here's the PR for registration:

https://github.com/JuliaRegistries/General/pull/3814

**Comment by PhilipVinc** [comment]
What about moving the declaration (and only the declaration) of modules like  timeevolution and steadystate in QuantumOpticaBase, so that third party packages can expand those namespace without depending directly on the whole QO.jl?
Il 25 set 2019, 18:27 +0200, David Plankensteiner <notifications@github.com>, ha scritto:
