### ISSUE TITLE
LazyTensor and FFTOperators ?

### ISSUE THREAD

**Issue by savowe** [qojulia/QuantumOptics.jl#264]
Hello.
Is it currently possible to achieve time-propagation of a compoung system with internal and external degrees of freedom ( e.g. Hilbert space of `NLevelBasis(2)⊗PositionBasis(x_min, x_max, N_x)`, with a Hamiltonian for the external parts in the form `1⊗V(x)+1⊗p^2/2`) using the FFT Operators and not numerical diagonalization? 
The `LazyTensor` is only able to work on sparse and dense operators and therefore need to be used before application of `LazyProduct` and `LazySum`. 
However, one can not make a tensorproduct of a sparse and a FFTOperator:
```
using QuantumOptics
internal_basis = NLevelBasis(2)
position_basis = PositionBasis(-5, 5, 1024)
momentum_basis = MomentumBasis(position_basis)
Tpx = transform(momentum_basis, position_basis)
Txp = dagger(Tpx)
x = position(position_basis)
p = momentum(momentum_basis)
# LazyTensor of internal degree of freedom and kinetic operator in momentum basis (meant as 1⊗V(x)+1⊗p^2/2)
H_kin_p = LazyTensor(internal_basis⊗momentum_basis ,[2], [p])^2/2
# The naive thing does not work:
H_kin_x = LazyProduct(identityoperator(internal_basis) ⊗ Txp, H_kin_p, identityoperator(internal_basis) ⊗ Tpx)
```
Is there a workaround for that?

**Comment by david-pl** [comment]
The trick is to create the `FFTOperator` directly on the composite basis and then use a `LazyProduct`.
Changing your code like this should work:
```julia
using QuantumOptics
internal_basis = NLevelBasis(2)
position_basis = PositionBasis(-5, 5, 1024)
momentum_basis = MomentumBasis(position_basis)
Tpx = transform(internal_basis⊗momentum_basis, internal_basis⊗position_basis)
Txp = dagger(Tpx)
x = position(position_basis)
p = momentum(momentum_basis)
H_kin_p = one(internal_basis)⊗p
H_kin_x = LazyProduct(Txp, H_kin_p, Tpx)
```

**Comment by savowe** [comment]
Indeed, it works. Thank you
