### ISSUE TITLE
can't install QuantumOptics package

### ISSUE THREAD

**Issue by liorella** [qojulia/QuantumOptics.jl#268]
hello,

I've been trying to install QuantumOptics.jl in JuliaPro and I get this message:

ERROR: Unsatisfiable requirements detected for package QuantumOptics [6e0679c1]:
 QuantumOptics [6e0679c1] log:
 ├─possible versions are: [0.5.5, 0.6.0-0.6.8, 0.7.0-0.7.3] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.5.5, 0.6.0-0.6.8, 0.7.0-0.7.3]
 ├─restricted by julia compatibility requirements to versions: [0.5.5, 0.6.0-0.6.5, 0.7.1-0.7.3] or uninstalled, leaving only versions: [0.5.5, 0.6.0-0.6.5, 0.7.1-0.7.3]
 ├─restricted by compatibility requirements with FFTW [7a1cc6ca] to versions: [0.5.5, 0.6.0-0.6.8, 0.7.0, 0.7.2-0.7.3] or uninstalled, leaving only versions: [0.5.5, 0.6.0-0.6.5, 0.7.2-0.7.3]
 │ └─FFTW [7a1cc6ca] log:
 │   ├─possible versions are: [0.1.0-0.1.2, 0.2.0-0.2.4, 0.3.0, 1.0.0-1.0.1, 1.1.0, 1.2.0] or uninstalled
 │   └─restricted by julia compatibility requirements to versions: [0.1.0-0.1.2, 0.2.0-0.2.4, 0.3.0, 1.0.0-1.0.1, 1.1.0] or uninstalled
 ├─restricted by compatibility requirements with QuantumOpticsBase [4f57444f] to versions: [0.5.5, 0.6.0-0.6.8] or uninstalled, leaving only versions: [0.5.5, 0.6.0-0.6.5]
 │ └─QuantumOpticsBase [4f57444f] log:
 │   ├─possible versions are: 0.1.0-0.1.4 or uninstalled
 │   ├─restricted by julia compatibility requirements to versions: 0.1.1-0.1.4 or uninstalled
 │   └─restricted by compatibility requirements with FFTW [7a1cc6ca] to versions: 0.1.0 or uninstalled, leaving only versions: uninstalled
 │     └─FFTW [7a1cc6ca] log: see above
 └─restricted by compatibility requirements with RecursiveArrayTools [731186ca] to versions: [0.6.6-0.6.8, 0.7.0-0.7.3] or uninstalled — no versions left
   └─RecursiveArrayTools [731186ca] log:
     ├─possible versions are: [0.16.0-0.16.3, 0.17.0-0.17.2, 0.18.0-0.18.6, 0.19.0-0.19.1, 0.20.0, 1.0.0-1.0.2, 1.1.0-1.1.1, 1.2.0-1.2.1, 2.0.0-2.0.5, 2.1.0-2.1.2, 2.2.0, 2.3.0-2.3.1] or uninstalled
     ├─restricted by julia compatibility requirements to versions: [0.16.0-0.16.3, 0.17.0-0.17.2, 0.18.0-0.18.6, 0.19.0-0.19.1, 0.20.0, 1.0.0-1.0.2, 1.1.0-1.1.1, 1.2.0-1.2.1, 2.0.0-2.0.5, 2.1.0-2.1.2, 2.2.0] or uninstalled
     ├─restricted by compatibility requirements with DifferentialEquations [0c46a032] to versions: [1.0.0-1.0.2, 1.1.0-1.1.1, 1.2.0-1.2.1, 2.0.0-2.0.5, 2.1.0-2.1.2, 2.2.0, 2.3.0-2.3.1], leaving only versions: [1.0.0-1.0.2, 1.1.0-1.1.1, 1.2.0-1.2.1, 2.0.0-2.0.5, 2.1.0-2.1.2, 2.2.0]
     │ └─DifferentialEquations [0c46a032] log:
     │   ├─possible versions are: [5.0.0, 5.1.0, 5.2.0-5.2.1, 5.3.0-5.3.1, 6.0.0, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.6.0, 6.7.0, 6.8.0, 6.9.0, 6.10.0-6.10.1, 6.11.0, 6.12.0, 6.13.0] or uninstalled
     │   └─restricted to versions 6.8.0 by an explicit requirement, leaving only versions 6.8.0
     └─restricted by compatibility requirements with QuantumOptics [6e0679c1] to versions: [0.16.0-0.16.3, 0.17.0-0.17.2, 0.18.0-0.18.6, 0.19.0-0.19.1, 0.20.0, 2.0.0-2.0.5, 2.1.0-2.1.2, 2.2.0, 2.3.0-2.3.1], leaving only versions: [2.0.0-2.0.5, 2.1.0-2.1.2, 2.2.0]
       └─QuantumOptics [6e0679c1] log: see above

my other installed pacakges are:

  "Juno"                  => v"0.7.2"
  "DifferentialEquations" => v"6.8.0"
  "IJulia"                => v"1.20.0"
  "Plots"                 => v"0.26.3"
  "Atom"                  => v"0.11.2"

what could be causing this incompatibility?

Thanks!

**Comment by PhilipVinc** [comment]
Differential equations possibly. Try removing it...
Il 8 mag 2020, 16:31 +0200, liorella <notifications@github.com>, ha scritto:

**Comment by david-pl** [comment]
@liorella Which Julia version are you on? There could be issues with v1.1 or v1.2. If that's the case try updating your Julia.

**Comment by david-pl** [comment]
I'm assuming this has been solved. Comment if that's not the case.
