### ISSUE TITLE
Make SparseOperator versions of subspace projectors?

### ISSUE THREAD

**Issue by saulpila** [qojulia/QuantumOptics.jl#277]
The functions `projector` from subspace.jl always return DenseOperators. Could you implement versions which return sparse operators? It is just a matter of replacing `zeros` with `SparseArrays.spzeros `and `DenseOperator `with `SparseOperator`. 
Oftentimes these projection matrices have lots of zeros, so it is convenient to have a sparse version available.

Thanks!

**Comment by david-pl** [comment]
On the latest master branch of QuantumOpticsBase.jl you can now do `projector(b1,b2;sparse=true)` to obtain a sparse operator version of the projector.

**Comment by saulpila** [comment]
Thank you so much! That's great!
