### ISSUE TITLE
Wigner function transposed

### ISSUE THREAD

**Issue by irojkov-ph** [qojulia/QuantumOptics.jl#280]
Hi there !

I have a small issue and I don't know if it's my fault (I am new to Julia) or if it's a bug in the current implementation of the Wigner function. Here is what I have: 

When I run (note the size difference between xvec and yvec):
```
xvec=[-5:.05:5;]
yvec=[-5:.05:2;]
W = wigner(state,xvec,yvec);
```
And try to plot it using:
```
contourf(xvec,yvec,W,100,cmap=ColorMap("RdBu"))
```
I have an error. However, if I do:
```
contourf(yvec,xvec,W,100,cmap=ColorMap("RdBu"))
```
The command runs, but I obtain a shorter xaxis instead of a shorter yaxis. It obviously comes from a non transposed W array, but my question is: should I always do it myself ? Or is it a bug in the `wigner` function ?

Thanks in advance :)
Ivan.

Btw: your QuantumOptics.jl is awesome, pleasant to use !

**Comment by david-pl** [comment]
Hi Ivan,

This is something that has always puzzled me a bit about `PyPlot`. Somehow, the dimensions are swapped in `countour` plots. To get what you want, you can just transpose the Wigner function, i.e.

```julia
contourf(xvec,yvec,W')
```

should give you the right x and y axis. This has nothing to do with QuantumOptics.jl though. Good to know you find the package useful!
