### ISSUE TITLE
Supporting Fock "offset" like qutip

### ISSUE THREAD

**Issue by Krastanov** [qojulia/QuantumOptics.jl#289]
When working with almost coherent states or with almost Fock states of specific number, it is convenient to have a basis that has not only maximal number cutoff, but also minimal number cutoff. See the `offset` parameter in http://qutip.org/docs/latest/apidoc/functions.html?highlight=destroy#qutip.operators.destroy

This does not seem to be currently supported here, right?

**Comment by david-pl** [comment]
This would be a good feature to have, but you're right, it's currently not supported. It will be rather straightforward to do the construction part for operators, but I'm not sure if other methods (e.g. the `wigner` function) will need changes too. I'll look into it.

**Comment by david-pl** [comment]
Alright, I started implementing this, see #290 and https://github.com/qojulia/QuantumOpticsBase.jl/pull/14. As I suspected the basics are quite simple, but updating the phase-space methods is a bit tricky. I'll need more time for that.

**Comment by Krastanov** [comment]
Oh, wow, this was fast! Thank you! It seems to be at feature-parity with qutip who also lack phase space methods https://github.com/qutip/qutip/issues/1417

Actually, on reading https://github.com/qojulia/QuantumOptics.jl/blob/master/src/phasespace.jl , maybe I am misunderstanding, but it seems the `qfunc` should already work even with an offset. But the use of `_clenshaw` probably needs to be updated? I am still getting accustomed to the code base, hence I can not yet contribute these changes myself.

**Comment by david-pl** [comment]
Thanks for the reference!
Yes, I already updated `qfunc`, but it's the `wigner` function or more specifically (as you say) the `_clenshaw` part that needs to be changed still. Additionally we have the `transform` functionality in QuantumOpticsBase with which you can map a `FockBasis` onto a `PositionBasis`, which also needs to be updated.

**Comment by david-pl** [comment]
This is now available in v0.8.4.
