### ISSUE TITLE
unresolved merge conflict in the API documentation

### ISSUE THREAD

**Issue by Krastanov** [qojulia/QuantumOptics.jl#292]
The `<<<` and `===` symbols around https://docs.qojulia.org/api/#API:-Direct-sum-1 make it look like there has been an unresolved merge conflict in the documentation.

**Comment by david-pl** [comment]
Thanks for reporting that, I must have missed it. I'll update the docs shortly.

**Comment by david-pl** [comment]
Alright, should be good now.
