### ISSUE TITLE
Support for OrdinaryDiffEq version 6

### ISSUE THREAD

**Issue by ruvilecamwasam** [qojulia/QuantumOptics.jl#328]
Thanks for all the work building this package, _QuantumOptics.jl_ has been very useful to me. I've recently been doing some work in PDEs, and am trying to install the package _MethodOfLines_. Unfortunately this leads to unsatisfiable requirements for the _OrdinaryDiffEq_ package.

_QuantumOptics v1.0.3_ supports _OrdinaryDiffEq_ versions 4.0.0-5.71.0. However some packages (such as _MethodOfLines_) require version 6. Is it possible to update _QuantumOptics_ to support version 6 of _OrdinaryDiffEq_?

The full error message when I run `add MethodOfLines` is:
```
ERROR: Unsatisfiable requirements detected for package OrdinaryDiffEq [1dea7af3]:
 OrdinaryDiffEq [1dea7af3] log:
 ├─possible versions are: 4.0.0-6.7.1 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 4.0.0-6.7.1
 ├─restricted by compatibility requirements with MethodOfLines [94925ecb] to versions: 6.0.0-6.7.1
 │ └─MethodOfLines [94925ecb] log:
 │   ├─possible versions are: 0.1.0-0.2.0 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.2.0
 └─restricted by compatibility requirements with QuantumOptics [6e0679c1] to versions: 4.0.0-5.71.0 — no versions left
   └─QuantumOptics [6e0679c1] log:
     ├─possible versions are: 0.5.5-1.0.3 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.5.5
```

**Comment by ChristophHotter** [comment]
@ruvilecamwasam it should work now with the new version 1.0.4.
