### ISSUE TITLE
Different result from QuTip 4.7.0 with the same parameters

### ISSUE THREAD

**Issue by Lockonchen** [qojulia/QuantumOptics.jl#342]
I tried to simulate the JC model with some externally driven pulses. My codes are here: https://github.com/Lockonchen/Simulate_Transmon/blob/main/Singleshot%20cavity-reset.ipynb

This result seems reasonable so it is good, but I got largely different results in QuTip with the same parameter sets. It is really anominal. 

One of my guesses is that QuantumOptics.jl and QuTip have different way of coping with collapse operator, because the non-dissipative case of them seems the same.

**Comment by ChristophHotter** [comment]
Hi @Lockonchen,
The `rates` kwarg uses the real rates, not the square root of them.
You need to use e.g. kappa instead of sqrt(kappa).

If you don't use rates, then you can e.g. J=[sqrt(kappa)*a] for the jump.

**Comment by Lockonchen** [comment]
> Hi @Lockonchen, The `rates` kwarg uses the real rates, not the square root of them. You need to use e.g. kappa instead of sqrt(kappa).
> 
> If you don't use rates, then you can e.g. J=[sqrt(kappa)*a] for the jump.

**Comment by Lockonchen** [comment]
@ChristophHotter Thanks so much for correcting my inappropriate use of the kwarg. It was a tricky one for me. 

It is nice that these two packages benchmark each other!
