### ISSUE TITLE
moving to codecov 4

### ISSUE THREAD

**Issue by Krastanov** [qojulia/QuantumOptics.jl#400]
codecov is changing how authentication works and only someone with admin rights in the organization can make the necessary change

@david-pl , could you add a global CODECOV_TOKEN token for the organization (it needs to be copied from the codecov settings page)? It should be added in https://github.com/organizations/qojulia/settings/secrets/actions

Here is a PSA about this https://discourse.julialang.org/t/psa-new-version-of-codecov-action-requires-additional-setup/109857

I can take care of updating the workflows as necessary after that.

**Comment by david-pl** [comment]
@Krastanov Thanks for keeping us up to date with all these maintenance things. I'll take care of it as soon as I can.

**Comment by david-pl** [comment]
@Krastanov should be good to go! Let me know if you run into any issues.

**Comment by Krastanov** [comment]
It seems codecov reports properly on PRs. Hopefully we have not missed anything. Closing this.
