### ISSUE TITLE
Registering version bump to `v1.1.2` failed

### ISSUE THREAD

**Issue by leburgel** [qojulia/QuantumOptics.jl#419]
It seems the attempt to register `v1.1.2` [here](https://github.com/qojulia/QuantumOptics.jl/commit/7961376d4a64ff68b24e1513f30e22dde87c295b#comments) failed; see the comments on [the corresponding General registry PR](https://github.com/JuliaRegistries/General/pull/115755).

As far as I can tell the problem is the Julia version compat being bumped to `v1.10` [here](https://github.com/qojulia/QuantumOptics.jl/pull/404), which is apparently not allowed to be tagged as a patch release?

**Comment by david-pl** [comment]
Oh, my bad, I thought that was already released. @apkille any reason this should be held back? Otherwise, I'll just bump to v1.2.

**Comment by apkille** [comment]
> Oh, my bad, I thought that was already released. @apkille any reason this should be held back? Otherwise, I'll just bump to v1.2.

@david-pl bumping to v1.2 is fine with me!

**Comment by david-pl** [comment]
Alright, thanks for the response @apkille. And thanks for pinging me here @leburgel, I honestly missed the response in the registry PR. Just registered v1.2, let's see if that gets merged.

**Comment by david-pl** [comment]
Alright, looks good now.
