### ISSUE TITLE
Optimization Problem of Many Body Operator

### ISSUE THREAD

**Issue by Umut-Can-Physics** [qojulia/QuantumOptics.jl#424]
Many body operator in the module `manybodyoperator(basis::ManyBodyBasis, op)` works slowly. My method is faster than module's method such as
`for i in 1:N
        for j in 1:N
            mb_op += op.data[i,j] * transition(ManyBodyBasis, i, j)
        end
    end
`
As you can see even having nested loop (dimension is N^2), my method still faster than original one. What is the fastest way to construct many body operator? Note that my problem dimension generally is from N=50 up to N=100.

**Comment by Umut-Can-Physics** [comment]
Here is an example
```
using BenchmarkTools
using QuantumOptics
# FIRST METHOD
N = 64
b = NLevelBasis(N)
op = randoperator(b)
M = 2
s = bosonstates(b, [M])
mb = ManyBodyBasis(b, s)
mb_op = manybodyoperator(mb, op) # MB OPERATOR 1
# SECOND METHOD
sparse_mb_op = SparseOperator(mb) # MB OPERATOR 2
for i in 1:N 
    for j in 1:N 
        sparse_mb_op += op.data[i,j] * transition(mb, i, j)  
    end 
end 
```
Note that two operator ` MB OPERATOR 1` and `MB OPERATOR 2` are the same but first method is so slow, WHY? Also, I need to speed up the second method.

**Comment by Umut-Can-Physics** [comment]
Update: Now, I use the following methode that is faster than the other methods.
```
using BenchmarkTools
using QuantumOptics
using LinearAlgebra
using Base.Threads

# Define the system and operator
N = 64
b = NLevelBasis(N)
op = randoperator(b)
M = 2
s = bosonstates(b, [M])
mb = ManyBodyBasis(b, s)

function MB_Op(mb, op)
    # Prepare a SparseOperator for each thread
    n_threads = Threads.nthreads()
    thread_results = [SparseOperator(mb) for _ in 1:n_threads]

    # Parallel loop with independent storage for each thread
    @threads for i in 1:N
        local_op = thread_results[threadid()]
        for j in 1:N
            if op.data[i, j] != 0  # Skip zero entries for efficiency
                local_op += op.data[i, j] * transition(mb, i, j)
            end
        end
        thread_results[threadid()] = local_op  # Ensure the result is stored in thread_results
    end

    # Combine the results from all threads
    sparse_mb_op = sum(thread_results)

    return sparse_mb_op
end
```

**Comment by apkille** [comment]
How are you benchmarking the two methods? I'm getting that `manybodyoperator` is way faster than your method:
```
julia> @btime manybodyoperator($mb, $op)
  108.003 ms (6 allocations: 66.02 MiB)

julia> @btime MB_Op($mb, $op)
  2.441 s (237647 allocations: 12.32 GiB)
```

**Comment by Umut-Can-Physics** [comment]
I have a question what is the typeof the following variable, called `SparseOpPureType`:
`manybodyoperator_1(mb::ManyBodyBasis, op::SparseOpPureType)`
And it is defined as 
`const SparseOpPureType{BL,BR} = Operator{BL,BR,<:SparseMatrixCSC}`.
Can you give an example about using of that kind of operator?

**Comment by Krastanov** [comment]
Most of the operators used in this library are represented as sparse matrices.

```
julia> using QuantumOpticsBase

julia> sigmax(SpinBasis(1//2))
Operator(dim=2x2)
  basis: Spin(1/2)sparse([2, 1], [1, 2], ComplexF64[1.0 + 0.0im, 1.0 + 0.0im], 2, 2)

julia> sigmax(SpinBasis(1//2)) |> typeof
Operator{SpinBasis{1//2, Int64}, SpinBasis{1//2, Int64}, SparseArrays.SparseMatrixCSC{ComplexF64, Int64}}

julia> typeof(sigmax(SpinBasis(1//2))) <: QuantumOpticsBase.SparseOpPureType
true
```

Sparse operators are used because multiplying with them is much faster if the operator has a lot of zeros components in the given basis.

**Comment by Umut-Can-Physics** [comment]
Here is complete example regarding optimization of `manybodyoperator` function. Although, study with  `QuantumOpticsBase.SparseOpPureType`, execution time is still slow with relatively small parameters i.e. 2 particles on 8x8 square lattice. My dream is calculating MB operator for bigger system such as 3 to 5 particles on maximum 10x10 square lattice.
```
using QuantumOptics
using SparseArrays

# Lattice Site Basis
N = 8*8
b = NLevelBasis(N)
dim = only(b.shape)
println("Single particle dimension = ", dim)

# Random sparse single particle operator
op = sprand(Bool, dim, dim, 0.01)
op = Operator(b, op)

# Total number of particle
M = 2

# Many Body Basis
s = bosonstates(b, [M])
mb = ManyBodyBasis(b, s)
dim_mb = only(mb.shape)
println("Many Body dimension = ", dim_mb)

# Many Body Operator
println("Is single particle operator sparse : ",typeof(op) <: QuantumOpticsBase.SparseOpPureType, "\n 
MB process is started...")
mb_op = manybodyoperator(mb, op);
println("MB is constructed!")
```
My system: i7-11th Gen. & 32 Ram
